#!/usr/bin/env ruby

Dir.glob('./lib/*.rb').each { |file| require file }

require 'progressbar'
require 'parallel'

PERCENT_IDENTITY = 80
CUTOFF = 5
BANDWIDTH = nil

class Phylograph
  def self.run!
    parse_arguments
    
    # COMPUTE CLUSTERS
    
    $stderr.puts "Computing Clusters"
    clusters = Hash.new
    
    @options[:filenames].each do |filename|
      $stderr.puts " - #{filename}"
      clusters[filename] = Cluster.compute_clusters PERCENT_IDENTITY, filename
    end

    # ALIGN CLUSTERS
    
    $stderr.puts "Interior Alignments"
    clusters.each_key do |filename|     
      $stderr.puts " - #{filename}" 
      sequences = clusters[filename][:reps].values
      clusters[filename][:scores] = pairwise_align sequences, sequences
      break
    end
    
    $stderr.puts "Align samples"
    set_a = clusters[clusters.keys[0]][:reps].values
    set_b = clusters[clusters.keys[1]][:reps].values
#    scores_between_samples = pairwise_align set_a, set_b
    clusters[:both] = Hash.new
#    clusters[:both][:scores] = scores_between_samples
    
    # Create adjacency matrices from scores
    # 1,2, 1,3, ... = 1->2 & 1->3
    
    adjacency_matrix = create_adjacency_matrix clusters.first[1][:scores]
    
    graph = Graph.make_graph adjacency_matrix
    p graph.write_to_graphic_file(fmt='png', dotfile="graph")
    
    
  end
end

Phylograph.run!